/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2020-08-06 05:54:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.tools.RequestUtil;
import com.esafenet.beans.client.ClientInfo;
import com.esafenet.dao.client.ClientDao;
import com.esafenet.util.CDGUtil;
import java.net.URLDecoder;
import com.esafenet.i18n.I18nProperyValueReplace;
import com.esafenet.i18n.ReadProperties;
import com.esafenet.ta.util.CookieUtil;
import org.apache.commons.lang3.StringUtils;

public final class clientDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/client/../languageApplicationResources.jsp", Long.valueOf(1592273151574L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.esafenet.beans.client.ClientInfo");
    _jspx_imports_classes.add("com.esafenet.ta.util.CookieUtil");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("com.esafenet.i18n.I18nProperyValueReplace");
    _jspx_imports_classes.add("com.esafenet.i18n.ReadProperties");
    _jspx_imports_classes.add("com.esafenet.dao.client.ClientDao");
    _jspx_imports_classes.add("com.esafenet.util.CDGUtil");
    _jspx_imports_classes.add("com.common.tools.RequestUtil");
    _jspx_imports_classes.add("org.apache.commons.lang3.StringUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

		
	ReadProperties rp = null;
	if (session.getAttribute("rp") == null) {
		String language = CookieUtil.getCookie(request,response,"CDGServerLanguage");
		if(StringUtils.isNotBlank(language)){
			rp = ReadProperties.getInstance(language);
			session.setAttribute("rp", rp);
		}else{
			rp = ReadProperties.getInstance("zh");
			session.setAttribute("rp", rp);
		}
	} else {
		String language = CookieUtil.getCookie(request,response,"CDGServerLanguage");
		rp = (ReadProperties)session.getAttribute("rp");
		if(!rp.getlanguage().equals(language) ){
			if(StringUtils.isNotBlank(language)){
				rp = ReadProperties.getInstance(language);
				session.setAttribute("rp", rp);
			}
		}
	}

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      com.org.acl.LoginMng loginMng = null;
      synchronized (session) {
        loginMng = (com.org.acl.LoginMng) _jspx_page_context.getAttribute("loginMng", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (loginMng == null){
          loginMng = new com.org.acl.LoginMng();
          _jspx_page_context.setAttribute("loginMng", loginMng, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

	if (loginMng == null || !loginMng.isLogin()) {
		response.sendRedirect("../loginExpire.jsp");
		return;
	}

      out.write('\r');
      out.write('\n');
 
	String machinename = RequestUtil.getParameter(request,"machinename","");
	String fromPage = RequestUtil.getParameter(request,"fromPage","");
	String machineId = RequestUtil.getParameter(request,"machineId","");
	machineId = URLDecoder.decode(machineId, "utf-8");
	
	String clientUserId= RequestUtil.getParameter(request,"clientUserId","");
	String safetyGroupId = RequestUtil.getParameter(request,"safetyGroupId","");
	int currPage = RequestUtil.getIntParameter(request,"curpage",1); //当前是第几页
	String organiseId = request.getParameter("organiseId");
	String subgroupState = RequestUtil.getParameter(request, "subgroupState", "0");
	
	ClientDao cDao=new ClientDao();
	ClientInfo info=cDao.findClientById(machineId);
	
	
	
	String searchParam = RequestUtil.getParameter(request, "searchParam", "");//模湖查询所有。
	
	String beginDate = RequestUtil.getParameter(request, "beginDate","");//开始日期
	if(beginDate.equals("")){
		beginDate = CDGUtil.getCurrentTime().substring(0, 10);
	}
	String endDate = RequestUtil.getParameter(request, "endDate", "");//结束日期
	if(endDate.equals("")){
		endDate = CDGUtil.getCurrentTime().substring(0, 10);
	}
	
	String clientStauts = RequestUtil.getParameter(request, "clientStauts", "");//客户端类型
	if(clientStauts == null || clientStauts.length() == 0){
		clientStauts = "-1";
	}

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>");
      out.print(rp.getString("global.sjxlfhdlpxt"));
      out.write("</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../style/style2/style.css\"\r\n");
      out.write("\t\t\ttype=\"text/css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/DataGrid.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/commons.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/prototype-1.6.0.2.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/verify.js\"></script>\r\n");
      out.write("<script language=\"javascript\"> \r\n");
      out.write("\tfunction returns(){\r\n");
      out.write("\t\tparent.document.getElementById(\"frmUserList\").height=\"700px\";\r\n");
      out.write("\t\tparent.document.getElementById(\"frmUserList\").src=\"");
      out.print(fromPage);
      out.write("?curpage=");
      out.print(currPage);
      out.write("&organiseId=");
      out.print(organiseId);
      out.write("&amp;searchParam=");
      out.print(searchParam);
      out.write("&subgroupState=");
      out.print(subgroupState);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\t//提交\r\n");
      out.write("\tfunction doSub(){\r\n");
      out.write("\t\tvar messageVal=document.getElementById(\"message\").value;\r\n");
      out.write("\t\tif(!isRightFileName(messageVal)){\r\n");
      out.write("\t\t   alert(\"");
      out.print(rp.getString("zdgl.zdgl.zdxxbnbhzxtszf"));
      out.write("\"+\"!@#$%^&*()\\\\/?\\'\\\":<>|\");\r\n");
      out.write("\t\t   return ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(isNull2(\"message\")){\r\n");
      out.write("\t\t\talert(\"");
      out.print(rp.getString("zdgl.zdgl.zdxxbnwk") );
      out.write("\");\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(messageVal.length>50){\r\n");
      out.write("\t\t\talert(\"");
      out.print(rp.getString("zdgl.zdgl.zdxxbdcgcd") );
      out.write("\");\r\n");
      out.write("\t\t\treturn ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar iszx = \"");
      out.print(info.getField04()!=null && info.getField04().equals("1"));
      out.write("\";\r\n");
      out.write("\t\tif(iszx==\"false\"||iszx==false){\r\n");
      out.write("\t\t\talert(\"");
      out.print(rp.getString("zdgl.zdgl.clientstates") );
      out.write("\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.myForm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body  class=\"main_frame\">\r\n");
      out.write("\t\t<form action=\"OfflineSmartSec\" method=\"post\" name=\"myForm\" id=\"myForm\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"command\" id=\"command\" value=\"ClientSession\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"fromurl\" id=\"fromurl\" value=\"clientDetails.jsp?organiseId=");
      out.print(organiseId );
      out.write("&subgroupState=");
      out.print(subgroupState);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"machineId\" id=\"machineId\" value=\"");
      out.print(machineId );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"machinename\" id=\"machinename\" value=\"");
      out.print(machinename );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"currPage\" id=\"currPage\" value=\"");
      out.print(currPage);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"safetyGroupId\" id=\"safetyGroupId\" value=\"");
      out.print(safetyGroupId);
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"fromPage\" id=\"fromPage\" value=\"");
      out.print(fromPage );
      out.write("\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"clientUserId\" id=\"clientUserId\" value=\"");
      out.print(clientUserId );
      out.write("\">\r\n");
      out.write("<table align=\"center\" class=\"DataGrid\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\t\t\tcellspacing=\"1\" width=\"95%\">\r\n");
      out.write("\t<tr class=\"DataGridThead\" >\r\n");
      out.write("\t\t<td colspan=\"10\" align=\"center\">\r\n");
      out.write("\t\t\t<!-- 表格标题 -->\r\n");
      out.write("\t\t\t");
      out.print(rp.getString("zdgl.zdgl.zdhh") );
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("terminal.zdbh") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"30%\"> \r\n");
      out.write("\t\t");
      out.print(info.getClientId() );
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("terminal.jqmc") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"30%\"> \r\n");
      out.write("\t\t");
      out.print(info.getClientName() );
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("log.jqIP") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"30%\"> \r\n");
      out.write("\t\t");
      out.print(info.getClientIp() );
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("terminal.zxzt") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"30%\"> \r\n");
      out.write("\t\t\t");

				if (info.getField04()!=null && info.getField05().equals("2")) {
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(rp.getString("terminal.yxz"));
      out.write("\r\n");
      out.write("\t\t\t");

				} else if (info.getField04()!=null && info.getField04().equals("1")) {
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(rp.getString("terminal.zzsyz"));
      out.write("..\r\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(rp.getString("terminal.wsy"));
      out.write("\r\n");
      out.write("\t\t\t");

				}
		   
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("zdgl.zdgl.dqdlyh") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"70%\"> \r\n");
      out.write("\t\t");
      out.print(info.getUserId() );
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("zdgl.zdgl.dlsj") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"70%\"> \r\n");
      out.write("\t\t");
      out.print(info.getField03() );
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("zdgl.zdgl.schh") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"70%\"> \r\n");
      out.write("\t\t<textarea id=\"\" name=\"\" rows=\"3\" cols=\"50\" readonly=\"readonly\">");
      out.print(null==info.getMachineId()?"":info.getMachineId() );
      out.write("</textarea>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td colspan=\"2\" align=\"left\">");
      out.print(rp.getString("zdgl.zdgl.qsrnyfsdhhxx") );
      out.write("：</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridRow\">\r\n");
      out.write("\t<td width=\"30%\" align=\"right\">");
      out.print(rp.getString("zdgl.zdgl.xx") );
      out.write("：</td>\r\n");
      out.write("\t<td width=\"70%\"> \r\n");
      out.write("\t\t<textarea id=\"message\" name=\"message\" rows=\"3\" cols=\"50\"></textarea>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr class=\"DataGridThead\">\r\n");
      out.write("\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"");
      out.print(rp.getString("config.fs") );
      out.write("\" onclick=\"doSub()\">\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<input type=\"button\" onClick=\"javascript:returns()\"\r\n");
      out.write("\t\t\tvalue=\"");
      out.print(rp.getString("button.fh") );
      out.write("\">\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
